version: '2.4'
services:
  mongo1:
    extends:
      file: docker-compose.services.template.yml
      service: mongo1
  mongo2:
    extends:
      file: docker-compose.services.template.yml
      service: mongo2
  mongo3:
    extends:
      file: docker-compose.services.template.yml
      service: mongo3
  mongoclient:
    extends:
      file: docker-compose.services.template.yml
      service: mongoclient
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  api:
    build:
      context: .
      dockerfile: 'Dockerfile.local'
    command: "/bin/bash -c 'yarn && yarn start:debug'"
    env_file: .env
    restart: always
    volumes:
      - '.:/usr/src/app'
      - 'nest_test_deps:/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
  nest_test_deps: